#!/bin/bash

# error function uses for handling common error cases
function error(){
	local value=$1
	local num=$2

	if [ ${num} -eq 1 ]; then
		local str="version changing failed"
	elif [ ${num} -eq 2 ]; then
		local str="install prozone packages failed"
	elif [ ${num} -eq 3 ]; then
		local str="install nftables package failed"
	elif [ ${num} -eq 4 ]; then
		local str="motd service confirm failed"
	else
		local str="Fail!"
	fi

	if [ ${value} -ne 0 ]; then
		echo "Error : ${str}"
		exit 9
	fi
}

# start
echo "========= TmaxLinux version start changing ..."
sleep 1
echo "..."

echo -e "\n ========= Version Changing ..."
sleep 1

file_os="/etc/os-release.prev"
file_lsb="/etc/lsb-release.prev"

## file version checking and modifying
if [ ! -f "$file_os" ];then
	sudo cp /etc/os-release /etc/os-release.prev &&
	sudo cp /etc/lsb-release /etc/lsb-release.prev

	error $? 1

	echo 'NAME="TmaxLinux"
VERSION="TmaxLinux 4.1.1 (Bionic Beaver)"
ID=tmaxlinux
ID_LIKE=debian
PRETTY_NAME="TmaxLinux 4.1.1"
VERSION_ID="4.1.1"
VERSION_CODENAME=bionic
TMAXLINUX_CODENAME=bionic' >> $HOME/os-release

	echo 'DISTRIB_ID=Tmaxlinux
DISTRIB_RELEASE=4.1.1
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="TmaxLinux 4.1.1"' >> $HOME/lsb-release

	sudo mv $HOME/os-release /etc/os-release
	sudo mv $HOME/lsb-release /etc/lsb-release

	error $? 1

	sudo cp /etc/issue /etc/issue.prev &&
	sudo cp /etc/issue.net /etc/issue.net.prev

	error $? 1

	echo 'TmaxLinux 4.1.1 \n \l' >> $HOME/issue
	echo 'TmaxLinux 4.1.1' >> $HOME/issue.net

	sudo mv $HOME/issue /etc/issue
	sudo mv $HOME/issue.net /etc/issue.net

	error $? 1
	echo -e "\n ========= Changing version finished !!"

fi


## installing prozone packages
while true; do
	echo -e "\n ========= Do you want to install prozone packages? [y/n]"
	read answer

	if [ "$answer" = "y" ]; then
		echo -e "\n ========= Install prozone packages ..."
		sleep 1
		echo "..."

		sudo apt-get -y install vim gcc g++ libstdc++5 libaio1 libaio-dev unzip openssh-server openssh-client sshpass net-tools websockify python3 expect socat flex awscli curl procmail software-properties-common jq bridge-utils arptables iproute2 lxc qemu-kvm genisoimage cloud-utils openvpn quota nfs-kernel-server nfs-common rpcbind xmlstarlet libvirt-bin libvirt-dev virt-viewer qemu-system-x86 qemu-block-extra python-netaddr openjdk-8-jdk

		error $? 2

		sudo apt-get -y remove postfix

		error $? 2
		############################ It will be deprecated #######################
		sshpass -p 'tmax@23' scp -o StrictHostKeyChecking=no -r root@192.168.60.135:/root/temp/nftables ./

		cd $HOME/nftables
		sudo dpkg -i *.deb

		error $? 3
		
		echo -e "\n ========= Nftables version"
		nft -v
		###########################################################################
		break

	elif [ "$answer" = "n" ]; then
		echo -e "\n Prozone package is not installed"
		break	
	else
		echo "Wrong answer"
	fi
done

## motd service enable & motd-news service remove 
echo -e "\n ========= motd.service enable"
file="/etc/update-motd.d/50-motd-news.dpkg-dist"

if [ -f "$file" ]; then
	sudo mv /etc/update-motd.d/50-motd-news.dpkg-dist /etc/update-motd.d/50-motd-news
	error $? 4
	sudo systemctl restart motd-news.service
	echo -e "\n ========= motd.service restart sucess"
fi

echo -e "\n ========= motd.service finish"


echo -e "\n ========= motd.news remove"
motd_file="/var/cache/motd-news"
file_size_kb=`du -k "$motd_file" | cut -f1`

if [ -f "$motd_file" ]; then

	if [ "$file_size_kb" -ge 1 ]; then
		sudo mv /var/cache/motd-news /var/cache/copy.motd-news
		sudo echo "" > /var/cache/motd-news
	else
		sudo echo "" > /var/cache/motd-news
	fi

else
	sudo touch /var/cache/motd-news
fi
echo -e "\n ========= motd.news remove finish !!"

echo -e "-------------------------------------"
echo -e "Vesion Changed finished! Please reboot the server. 
And Check systemctl status is all running"
